name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
    - name: Codecov
      uses: codecov/codecov-action@v1.0.5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    - name: JSII Publish
      uses: udondan/jsii-publish@v0.8.3
      with:
        VERSION: ${{ steps.get_version.outputs.VERSION }}
        BUILD_SOURCE: true
        BUILD_PACKAGES: true
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      env:
        CI: true
